### ISSUE TITLE
Error sounds play when exploring `gitin log`

### ISSUE THREAD

**Issue by Soben** [isacikgoz/gitin#11]
Using iTerm, and installed via `brew`

I went straight into a repo and ran `gitin log` and used the arrow keys to explore. Interaction proceeded as expected, but every arrow key press triggered a sound from MacOS for an invalid interaction in the terminal.

**Comment by isacikgoz** [comment]
Thank you for the feedback, I was also aware of this issue and I forgot to implement the proposed solution [here](https://github.com/manifoldco/promptui/issues/49) 

A quick solution may be disabling terminal bells from the settings. Nevertheless I will apply a patch for this issue.

**Comment by Soben** [comment]
I normally disable sounds, which I'll probably do, but figured it was worth bug reporting 👍 

Thanks for the update!

**Comment by isacikgoz** [comment]
I've implemented proppsed suggestion, you can try it by building yourself or you can see it on the next release.

**Comment by isacikgoz** [comment]
I've just fixed it and it's merged to master. Please let me know if you still the issue. Also, feel free to open a new issue.
