### ISSUE TITLE
Lines cut off when viewing diff of file

### ISSUE THREAD

**Issue by grossjohann** [isacikgoz/gitin#14]
When I do `gitin status` and then select a file, or `gitin log` and then select a commit and then a file, in both cases it looks like I'm viewing the diff with `less`.  But long lines are cut off, and I can't scroll right, either.  I tried `-S` in `less`, thinking that would start wrapping lines, but it didn't work, either.

I'm sorry that my code base has such long lines, but nevertheless I have to live with it, so I'd like to see the right hand end of the line in my diff output, too.

**Comment by isacikgoz** [comment]
Thanks for the feedback @grossjohann I will push a quickfix for this to add `-S` option on `less`.

**Comment by isacikgoz** [comment]
@grossjohann It should be fixed with #15 You can get latest updates by building the app by yourself or you can wait for the next release.

**Comment by isacikgoz** [comment]
I've just implemented this and it's merged to master. Also, feel free to open a new issue if you need another feature.
