### ISSUE TITLE
Installer doesn't work if GOPATH contains multiple entries

### ISSUE THREAD

**Issue by Carpetsmoker** [isacikgoz/gitin#17]
Your installer doesn't work if GOPATH contains multiple entries:

    $ echo $GOPATH
    /home/martin/go:/home/martin/work

It tries to run stuff like:

    patch -d /home/martin/go:/home/martin/work/src/gopkg.in/libgit2/git2go.v27 -p1 < git2go.v27.patch

The solution is to change this:

    GOPATH_DIR:=$(shell go env GOPATH)

To something like:

    GOPATH_DIR:=$(shell go env GOPATH | cut -d: -f1)

(but I didn't test this solution at all).

**Comment by isacikgoz** [comment]
Thanks for the feedback @Carpetsmoker 

The better solution would be searching from GOPATH's for the projects we actually need. The workaround maybe something just as you proposed but we need to be sure that `libgit2`folder is in that `GOPATH`

I will happily accept a PR for this issue

ps: I never used multiple GOPATH's, When I require my projects needs to be somewhere else, I just create a symbolic link to GOPATH.

**Comment by isacikgoz** [comment]
Now it is like as you suggested, also you can give `GOPATH_BIN` arg as in input to `make install` if you want to work with a specific `$GOPATH`. I've just merged to master. Please let me know if you still the issue. Also, feel free to open a new issue.
