### ISSUE TITLE
Any ETA for Windows version?

### ISSUE THREAD

**Issue by SLMNBJ** [isacikgoz/gitin#18]

**Comment by isacikgoz** [comment]
Hello @SLMNBJ 

There are few obstacles with Windows:
- Need to build libgit2 for Windows 
- Need some tweaks such as: I use some unix commands like`less` sometimes that needs to be handled

After these, `gitin` can run on windows. I would appreciate help for this issue.

**Comment by isacikgoz** [comment]
Windows build requires some experiments, but I guess it should work on windows now. So, I am closing this issue for now due to inactivity. Thank you.
