### ISSUE TITLE
Only works from git repo's top level dir

### ISSUE THREAD

**Issue by Fuzion24** [isacikgoz/gitin#23]
`gitin` fails when you dont execute from the the top level git path.  

```
could not find repository from '/home/user/gitproject/some/sub/dir/'
```

Would be useful to walk the folder tree backwards to look for a git repo.

**Comment by Fuzion24** [comment]
May be a dupe of #6

**Comment by isacikgoz** [comment]
I've just fixed it and it's merged to master. Please let me know if you still the issue. Also, feel free to open a new issue.
