### ISSUE TITLE
[Feature Request] Keep search results when back to commit list

### ISSUE THREAD

**Issue by KevCui** [isacikgoz/gitin#26]
It would be cool if it's possible to keep search results when back to commits list. For ex:

gitin log -> type "/" -> type "add" -> arrow up/down -> enter 1 commit -> type "q" back to commits list

In this case, it shows the original commits list without applying search "add".

It would be cool to have the possibility to go back to the list with applying search "add". Maybe a hotkey "backspace" to go back to the filtered list?

**Comment by isacikgoz** [comment]
Thanks for the feedback @KevCui I need to work on this but it is a reasonable request.

**Comment by isacikgoz** [comment]
I've just implemented this and it's merged to master. Also, feel free to open a new issue if you need another feature.

**Comment by KevCui** [comment]
Amazing, thanks! :+1:
