### ISSUE TITLE
interactive hunk staging

### ISSUE THREAD

**Issue by ohle** [isacikgoz/gitin#27]
The one feature that still makes tig essential for me is interactive hunk staging, i.e. staging hunks from the diff view.

In tig, one can even stage (or un-stage) single lines.

**Comment by isacikgoz** [comment]
Hi @ohle thanks for the feedback and your suggestion. It is reasonable and it can be done *I guess*, but never used staging in that way. I can get some help for this request.

**Comment by isacikgoz** [comment]
Hi, @ohle. I implemented the hunk staging feature. Does it seem right?
![hunk_index](https://user-images.githubusercontent.com/2153367/52584600-8163d200-2e43-11e9-80fc-4bc83133d4f6.gif)

Haven't merged #39 to `master` yet.

Usage is:
- Press `p` on a file you wish to interactive hunk stage
- Select/unselect hunks with `<space>` 
- `q` quits and applies the patch

Features:
- You can apply to index
- You can remove from index

Not yet:
- Manage hunk lines

**Comment by ohle** [comment]
That looks great!

**Comment by isacikgoz** [comment]
I've just implemented this and it's merged to master. Also, feel free to open a new issue if you need another feature.
