### ISSUE TITLE
'brew install gitin' installs the macOS binary on linux

### ISSUE THREAD

**Issue by stephane-martin** [isacikgoz/gitin#29]
... and that doesn't really work ;)

**Comment by isacikgoz** [comment]
Thanks for the feedback @stephane-martin  I planned homebrew for mac distribution only. But, `brew` formula is hosted at [here](https://github.com/isacikgoz/homebrew-gitin). Feel free to add Linux support.

**Comment by isacikgoz** [comment]
Hello @stephane-martin, now it should be install-able via brew in Linux.

**Comment by stephane-martin** [comment]
Thanks. I still get the darwin binary when trying `brew install gitin`. Am i missing something ?

**Comment by isacikgoz** [comment]
I added this commit to my brew repository [531cf2f](https://github.com/isacikgoz/homebrew-taps/commit/531cf2fa6e814017652e1383fe3301989155dad7) which should install Linux binary if the OS is Linux
