### ISSUE TITLE
Show Author and Tags in `gitin log`

### ISSUE THREAD

**Issue by phauer** [isacikgoz/gitin#30]
Hi,
I really like gitin and I consider it as a replacement for [tig](https://github.com/jonas/tig). However, tig shows also the commit author and the tags in the commit overview. Especially the tags are very important to quickly see which commits made it into a release.

Keep on rocking with gitin!

**Comment by isacikgoz** [comment]
Hi @phauer thanks for the feedback. Actually, I implemented the tag feature but I guess it is not working somehow. I will attach ac7bb687eaefee5931427e6fe9d855df7f022ebc to the next PR.

Btw, thanks for the support, I really appreciate it. 💯

**Comment by isacikgoz** [comment]
I've just implemented this with #34 and it's merged to master. Also, feel free to open a new issue if you need another feature.

**Comment by phauer** [comment]
Wow, that was really fast. Thank you very much. I'll check it out asap.

**Comment by isacikgoz** [comment]
NP, just type `gitin log --tags` it will show tags like `git log` does. If you need additional use cases, just let me now.
