### ISSUE TITLE
Terminal's line-wrapping is changed

### ISSUE THREAD

**Issue by grossjohann** [isacikgoz/gitin#31]
When I enter `gitin`, it sets the terminal to not wrap lines.  It fails to revert back to the old state when quitting `gitin`, however.

I use version 0.1.0 installed via Homebrew on macOS 10.14.2 (Mojave).

More detailed description:

Open a terminal with a shell prompt.  Navigate to the root of a git clone.  Type the following command:

    echo $PWD $PWD $PWD $PWD $PWD $PWD

Assuming this prints a line longer than the terminal width, you will observe that the line is wrapped around to the next screen line.  (This is the default terminal behavior, as far as I know.)  (Add more `$PWD` if the line is too short for wrapping.)

Now invoke `gitin status`.  Wait for its output to appear.  Hit `q` to quit.

Now repeat the above `echo` command, and observe that the line is no longer wrapped.  Instead, it is cut off.

The expected behavior is that the line wraps, just like it did before I invoked `gitin status`.

I can now type `reset` at the terminal and then repeat the `echo` command again, and now it wraps properly.

I tested this with iTerm2 and with the built-in Terminal app, with the same results.

**Comment by isacikgoz** [comment]
Thanks for reporting this issue @grossjohann I will apply a partch for tihs issue. The commit 4d606fd1e99acf76801774acffb13a5420b3c9f9 will hopefully resolve this issue.

**Comment by isacikgoz** [comment]
I've just fixed it with #34 and it's merged to master. Please let me know if you still the issue. Also, feel free to open a new issue.
