### ISSUE TITLE
Stray "q" after quitting `gitin status` and `gitin log`

### ISSUE THREAD

**Issue by grossjohann** [isacikgoz/gitin#32]
Navigate to the root of a git repository.  Run `gitin status`.  Hit `q` to quit.  Observe that a stray "q" is printed before the next shell prompt.

For example, after `PS1='> '` (in bash), I see this:

    > gitin status
    q>

(It also happens with my default prompt, I just used a really simple prompt to clarify.)

**Comment by isacikgoz** [comment]
Thanks for reporting this issue @grossjohann I will apply a partch for tihs issue. The commit 4d606fd1e99acf76801774acffb13a5420b3c9f9 will hopefully resolve this issue.

**Comment by isacikgoz** [comment]
I hope this should be resolved with #34 and it's merged to master. Please let me know if you still the issue. Also, feel free to open a new issue.
