### ISSUE TITLE
[Feature Request] - Flag to list branches by date

### ISSUE THREAD

**Issue by mikeymurph77** [isacikgoz/gitin#36]
From the looks of it, it appears that the branches are organized alphabetically. It would be great to add a flag to sort them with latest at the top of the list.

Also since it shows remote branches as well, having another flag to show only local branches would be nice.

Great tool!

**Comment by isacikgoz** [comment]
Thanks for the feedback @mikeymurph77 I would happily add this feature to next release.

**Comment by isacikgoz** [comment]
Hi, @mikeymurph77. I've implemented your request. Does it seem right?
![opt](https://user-images.githubusercontent.com/2153367/52585385-a6594480-2e45-11e9-9867-e9b009b63c76.gif)

**Comment by isacikgoz** [comment]
I've just implemented this and it's merged to master. Also, feel free to open a new issue if you need another feature.

**Comment by mikeymurph77** [comment]
Perfect! Thanks @isacikgoz
