### ISSUE TITLE
[REQUEST] Contribution guide for MacOS

### ISSUE THREAD

**Issue by ybbond** [isacikgoz/gitin#37]
I am trying to contribute with my OSX machine, but it turns out that the guide cannot be followed easily (related to problem with `ldconfig`, and else). I am new to Go, btw.

Also, I am sure that there is some typo on https://github.com/isacikgoz/gitin#development-requirements (e.g. `pkg-confid`)

**Comment by isacikgoz** [comment]
Thanks for the support @ybbond If you are using macOS, actually, you don't need to build libgit2 v27 because you can install it via`brew install libgit2` then you can just download project with `go get github.com/isacikgoz/gitin` and start hacking. 

ps. I will fix typos in the next PR 👍

**Comment by isacikgoz** [comment]
I've just fixed it and it's merged to master. Please let me know if you still the issue. Also, feel free to open a new issue.
