### ISSUE TITLE
[Bug] Dirty exit after back from viewing commit

### ISSUE THREAD

**Issue by tuyenpm9** [isacikgoz/gitin#40]
Reproduce steps:
1. go into a repo
2. issue `gitin log`
3. press `enter`s to reach open a commit in view mode with `less`
4. press `q`s to quit to shell.

expected behavior is that we need only three `q` to exit from commit view mode but it actually took more, 4-5 `q` to exit.

after step 3, if I try to scroll using `ctrl-n` or `ctrl-p` it will print out chars after `Date:` `^N^N^N^P^P^P^N^N^N^Nqqq^C` - `^C` to force exit `gitin`.

**Comment by isacikgoz** [comment]
Hello, @tuyenpm9 Thanks for the feedback! Unfortunately, I cannot reproduce the same output. Whic OS and terminal emulator you are using?

**Comment by tuyenpm9** [comment]
I use archlinux and st terminal, but I'll close this issue due to out of time. thanks.
