### ISSUE TITLE
[Feature Request] Multiple UI view modes

### ISSUE THREAD

**Issue by tuyenpm9** [isacikgoz/gitin#42]
Command line options to `gitin` that enable it to change UI modes, currently work perfectly but give users multiple choices are better.

**Comment by isacikgoz** [comment]
Thanks for the feedback @tuyenpm9. Can you expand your request a little? I couldn't understand it :) e.g. Which UI modes you want?

**Comment by tuyenpm9** [comment]
Thanks, you had given different options branch/commit, would count for each UI.
