### ISSUE TITLE
[Feature request] Discard unstaged changes from status

### ISSUE THREAD

**Issue by ohle** [isacikgoz/gitin#44]
It would be nice to be able to reset (i.e. do `git checkout -- [file]` on) files marked as unstaged in the status view.

**Comment by isacikgoz** [comment]
Thanks for the feedback @ohle I can add this to the next PR.

Which hotkey would be approptirate for this operation? Consider that these are occupied
`<space>` -> add/reset
`<enter>` -> diff
`c` -> commit
`m` -> amend
`p` -> patch
`a` -> add all
`r` -> reset all
`q` -> quit

**Comment by ohle** [comment]
`tig` uses `!` for this, but if you'd rather use a letter, I guess one could use `u` (as in "undo")

**Comment by isacikgoz** [comment]
`!` is OK.  I've just implemented this and it's merged to master. Also, feel free to open a new issue if you need another feature.
