### ISSUE TITLE
Add support searching by commit id

### ISSUE THREAD

**Issue by kmyokoyama** [isacikgoz/gitin#47]
It'd be really nice if I could just type in part of the commit hash (instead of commit message) and `gitin log` be able to find it. This is a simple task I perform daily and gitin does not seem to support it yet.

Do you plan to add this kind of feature?

Thanks and good job!

**Comment by isacikgoz** [comment]
Thanks for the feedback @kmyokoyama This can be added to gitin, we should think about how can we add this to be more user friendly.

**Comment by isacikgoz** [comment]
I've just fixed it and it's merged to master. Please let me know if you still the issue. Also, feel free to open a new issue.

**Comment by kmyokoyama** [comment]
Hi, @isacikgoz. I've just tested this fix, but I'd like to understand better how it's supposed to work. Consider the scenario where I have the following commit history (from most recent to older):

188eb19
8aad642
3c9caf9
86c38c1
[many commits ago]
8d6b001

When I search for "86", it shows me as first option the commit 8d6b001, instead of (the expected) 86c38c1. When I search for "86c", then it shows me commit 86c38c1. Is this intentional?

Thank you.

**Comment by isacikgoz** [comment]
hey @kmyokoyama, It uses fuzzy-match algorithm which can be found [here](https://github.com/sahilm/fuzzy) And I feed it with commit msg + hash. Better match can be achieved with hash + msg combination. But it will reduce msg matching performance.

I guess, this should be configurable but I need some suggestions for this.

**Comment by kmyokoyama** [comment]
What if it was added a new key command e.g. `?` or `h` for hash searching instead of the usual `/`?

**Comment by isacikgoz** [comment]
I think it would be better to start with  `h:` to search for hash. e.g. type `/` then simply type `h:a1b2c3d` to find that hash. What do you think @kmyokoyama ?

**Comment by kmyokoyama** [comment]
It works, but I think it's a little more typing than just simply pressing `h` right after starting `gitin log`. Do you think it adds visual pollution to the options menu? I mean, having `Nav: ... select: ... quit: ... / toggles search and h toggles hash search` is too much? I believe it can be worked out if it's an issue.
