### ISSUE TITLE
Show a diff or file contents for untracked files/directories in `status`

### ISSUE THREAD

**Issue by kergoth** [isacikgoz/gitin#5]

**Comment by isacikgoz** [comment]
I think it can be done with this [solution](https://stackoverflow.com/a/52093887/1537318) basically detect de untracked  file and rather than using `git diff path/to/file`, we can use `git diff --no-index /dev/null path/to/file`. I will try this! Thanks for the feedback @kergoth

**Comment by kergoth** [comment]
That does sound viable, thanks for the quick response. I like the project so far. It feels like a lighter, less intrusive https://github.com/jonas/tig. The combination of not being fullscreen + the sub-command based approach is appealing to me.

**Comment by isacikgoz** [comment]
Thank you, the idea is exactly being a lightweight git assistant. There are plenty of full-screen alternatives such as [tig](https://github.com/jonas/tig), [grv](https://github.com/rgburke/grv), [lazygit](https://github.com/jesseduffield/lazygit) and so on.. But, I like to way just as you stated.

By the way, 7bd481aac8c23257b8f0270bb5e1d484e28361a0 made possible to see diff of untracked files. Once I find a solution on directories I will add it too.

**Comment by isacikgoz** [comment]
It seems that diff of directories is not easy and also not supported by `git` itself. I've just implemented this for files and it's merged to master. Also, feel free to open a new issue if you need another feature.
