### ISSUE TITLE
Add colour coding on gitin branch command

### ISSUE THREAD

**Issue by reobin** [isacikgoz/gitin#60]
The ```git branch -a``` command shows local branches in white, remote branches in red, and the currently checked out branch in green.

<img src="https://i.imgur.com/LiBfrfP.png" alt="git branch -a" />

It think the ```gitin branch``` could make good use of that colour coding.

Thanks for what you're doing with gitin, it makes my everyday git flow a lot neater!

**Comment by isacikgoz** [comment]
Hey @reobin thanks! I will definitely consider this. Why don't we test in the next release?
