### ISSUE TITLE
Unable to install from AUR of Manjaro

### ISSUE THREAD

**Issue by c02y** [isacikgoz/gitin#62]
When I tried to install gitin from AUR of Manjaro, there is error:
~~~
$ pacui i gitin
==> Error: Could not find all required packages:
    libgit2=1:0.27.8 (Wanted by: gitin)
    libgit2-glib=0.27.8 (Wanted by: gitin)
~~~

https://aur.archlinux.org/packages/gitin page says I have to downgrade my libgit2 to 0.27.8, but my current installed version is libgit2=1:1.0.0-1

There was another issue mentioning this libgit2 problem, like https://github.com/isacikgoz/gitin/issues/57 , does gitin really have to use exactly libgit2=1:0.27.8 and libgit2-glib=0.27.8?

**Comment by isacikgoz** [comment]
I updated dependency of `libgit2` to `v1.0.1`. Also `git2go` version is `v30.0.9` now. You can download the repo and run `make install` to use `gitin`. Please let me know if you get into any errors during the installation. We can add error cases (or, missing documentation etc.) into readme file.

**Comment by isacikgoz** [comment]
Closing this issue, feel free to re-open if necessary.
