### ISSUE TITLE
git2go 1.0

### ISSUE THREAD

**Issue by kimat** [isacikgoz/gitin#63]
Are there any plans to move towards a more recent git2go ?

It's unclear how long 0.27 will be supported.

cf. https://github.com/NixOS/nixpkgs/pull/86070#discussion_r417670942

**Comment by isacikgoz** [comment]
Thanks for bringing this up! I updated deps to `git2go/v30` and `libgit2/v1` :) Will release binaries soon. In the mean time you can build the with updated dependencies on `master` branch!
