### ISSUE TITLE
Can't see input on command line after exiting gitin

### ISSUE THREAD

**Issue by scrossan-crown** [isacikgoz/gitin#9]
After exiting gitin my teminal emulator doesn't show the input I am typing only the output of the commands.

![image](https://user-images.githubusercontent.com/30405149/52265149-4f2a1000-292b-11e9-819a-370bc9879cdc.png)

**Comment by isacikgoz** [comment]
Oops. It must be something related with hiding cursors when running `gitin` can you type `echo "\033[?25h"` ? Maybe it can fix it back.

**Comment by PatrickE94** [comment]
Reproducible by simply entering any submenu and then exiting. `reset` is of course a quickfix!

**Comment by scrossan-crown** [comment]
@isacikgoz `echo "\033[?25h"` didn't restore the cursor
@PatrickE94  `reset` worked

**Comment by PatrickE94** [comment]
@isacikgoz Another detail which might help in the debugging, slowly tapping `q` from a sub-menu in log mode works fine. But quickly tapping `q` almost always misses to reset the cursor.

**Comment by isacikgoz** [comment]
I've just fixed it and it's merged to master. Please let me know if you still the issue. Also, feel free to open a new issue.
